### ISSUE TITLE
Output coordinates question

### ISSUE THREAD

**Issue by Phlya** [XiaoTaoWang/HiCPeaks#2]
Hi, thank you very much for this tool, I have tried to use it and was pleasantly surprised - very easy to use and fast!

I however have a small question about the output coordinates of pyHICCUPS. What do they correspond to? What is the difference between `loc_1` and `centroid_x`? Sometimes they are the same, and sometimes they are not... And how is radius determined?

Thank you,
Ilya

**Comment by Phlya** [comment]
Basically, what is the correct way to convert the output to bedpe for visualization in e.g. HiGlass?

**Comment by XiaoTaoWang** [comment]
Hello, use ``loc_1`` and ``loc_2`` instead of ``centroid_x`` and ``centroid_y`` in post analysis and visualization, because ``(loc_1, loc_2)`` corresponds to the peak with the greatest interaction frequency in each cluster, while ``(centroid_x, centroid_y)`` just indicates the cluster centroid.

**Comment by XiaoTaoWang** [comment]
pyHICCUPS implements the greedy clustering algorithm proposed by the original paper (Rao et al. Cell. 2014), and the radius is defined as the Euclidean distance between the centroid of a cluster and the furthest peak pixel in the same cluster.

**Comment by Phlya** [comment]
Thank you very much for the explanation!
