### ISSUE TITLE
toCooler

### ISSUE THREAD

**Issue by buguashushu** [XiaoTaoWang/HiCPeaks#3]
HI
Thank you for your work. 
When I use the toCooler to change the matrix obtain from HiC-Pro into cool format, an error occured:

Traceback (most recent call last):
  File "/opt/conda/bin/toCooler", line 131, in <module>
    run()
  File "/opt/conda/bin/toCooler", line 112, in run
    from hicpeaks.utilities import Genome, balance
  File "/opt/conda/lib/python2.7/site-packages/hicpeaks/utilities.py", line 13, in <module>
    from cooler.io import create, parse_cooler_uri, CoolerMerger
ImportError: cannot import name parse_cooler_uri

so I edited the utilities.py as 

from cooler.util import binnify, parse_cooler_uri
from cooler.io import create
from cooler.reduce import CoolerMerger

and it passed. Please check and confirm.

**Comment by XiaoTaoWang** [comment]
Yeah, the latest version of cooler has a lot of changes in package organization. I have updated hicpeaks (0.3.2) to make compatible with cooler > 0.8. Thank you!

**Comment by buguashushu** [comment]
👍👍👍

**Comment by buguashushu** [comment]
> Yeah, the latest version of cooler has a lot of changes in package organization. I have updated hicpeaks (0.3.2) to make compatible with cooler > 0.8. Thank you!

👍👍👍
